import { useState, useEffect } from 'react'
import { Card, StatCard } from '../../components/ui/Card'
import { Button } from '../../components/ui/Button'
import { Download, TrendingUp, Activity, PieChart as PieChartIcon } from 'lucide-react'
import { AreaChart, Area, XAxis, YAxis, Tooltip as RechartsTooltip, ResponsiveContainer, PieChart, Pie, Cell, Legend } from 'recharts'
import { useAuth } from '../../context/AuthContext'
import { useToast } from '../../context/ToastContext'
import { supabase } from '../../supabase/client'
import { formatCurrencyTZS, formatCurrencyCompact } from '../../utils/formatters'
import { format } from 'date-fns'
import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import './AgentReports.css'

const COLORS = ['#00A651', '#003580', '#E40000', '#F5A623', '#7B2FBE']

export default function AgentReports() {
  const { user } = useAuth()
  const { error: toastError } = useToast()
  
  const [loading, setLoading] = useState(true)
  const [reportData, setReportData] = useState(null)
  const [timeframe, setTimeframe] = useState(30) // Default 30 days
  const [agentName, setAgentName] = useState('Agent')

  useEffect(() => {
    async function loadReportData() {
      try {
        setLoading(true)
        // Ensure user is an agent and get their ID
        const { data: u } = await supabase.from('users').select('agent_id').eq('id', user.id).single()
        if (!u?.agent_id) throw new Error("Agent ID missing")

        // Get Profile Name
        const { data: ag } = await supabase.from('agents').select('name').eq('id', u.agent_id).single()
        if (ag) setAgentName(ag.name)

        // Call our strict server-side reporting function
        const { data: cloudReport, error: rpcError } = await supabase.rpc('get_agent_performance_report', { 
          p_agent_id: u.agent_id, 
          p_days: timeframe 
        })

        if (rpcError) throw rpcError
        
        setReportData(cloudReport)
      } catch (err) {
        console.error("Report load error:", err)
        toastError('Report Error', 'Could not load performance data.')
      } finally {
        setLoading(false)
      }
    }

    if (user?.id) {
      loadReportData()
    }
  }, [user, timeframe, toastError])

  const downloadPDF = () => {
    if (!reportData) return
    
    // Create new PDF document
    const doc = new jsPDF()
    const pageWidth = doc.internal.pageSize.width
    const reportDate = format(new Date(), 'MMM dd, yyyy')

    // e-WAKALA Header
    doc.setFontSize(22)
    doc.setTextColor('#0F4C81') // E-wakala primary
    doc.text('e-WAKALA', 14, 20)
    
    doc.setFontSize(10)
    doc.setTextColor('#666666')
    doc.text('Regulated Agent Banking', 14, 26)

    // Report Title & Meta
    doc.setFontSize(16)
    doc.setTextColor('#000000')
    doc.text('Agent Performance Report', 14, 40)
    
    doc.setFontSize(10)
    doc.text(`Agent Name: ${agentName}`, 14, 48)
    doc.text(`Period: Last ${timeframe} Days`, 14, 54)
    doc.text(`Generated: ${reportDate}`, 14, 60)

    // Executive Summary Table
    const summaryData = [
      ['Total Volume Moved', formatCurrencyTZS(reportData.summary.total_volume)],
      ['Total Transactions', reportData.summary.total_count.toString()],
      ['Net Commission Earned', formatCurrencyTZS(reportData.summary.total_commission)],
      ['Success Rate', `${reportData.summary.success_rate}%`]
    ]

    autoTable(doc, {
      startY: 70,
      head: [['Key Metric', 'Value']],
      body: summaryData,
      theme: 'grid',
      headStyles: { fillColor: '#0F4C81' },
      styles: { fontSize: 11, cellPadding: 5 }
    })

    // Category Breakdown Table
    const lastY = doc.lastAutoTable.finalY + 15
    doc.setFontSize(14)
    doc.text('Breakdown by Transaction Type', 14, lastY)

    const categoryData = reportData.category_split.map(cat => [
      cat.name,
      formatCurrencyTZS(cat.value)
    ])

    autoTable(doc, {
      startY: lastY + 5,
      head: [['Type', 'Total Volume']],
      body: categoryData,
      theme: 'grid',
      headStyles: { fillColor: '#00A651' },
      styles: { fontSize: 10 }
    })

    // Footer
    doc.setFontSize(8)
    doc.setTextColor('#999999')
    const footerText = 'Confidential Report generated by e-WAKALA Core System.'
    doc.text(footerText, pageWidth / 2, doc.internal.pageSize.height - 10, { align: 'center' })

    // Save
    doc.save(`ewakala_report_${agentName.replace(/\s+/g, '_')}_${timeframe}d.pdf`)
  }

  // format chart data
  const chartData = reportData?.daily_trends?.map(d => ({
    ...d,
    dateStr: format(new Date(d.date), 'MMM dd')
  })) || []

  return (
    <div className="agent-reports animate-fadeIn">
      {/* Header */}
      <div className="agent-reports__header">
        <div>
          <h1 className="page-title">Performance Reports</h1>
          <p className="page-subtitle">Track your growth and commission earnings.</p>
        </div>
        <Button 
          variant="primary" 
          icon={<Download size={18} />} 
          label="Download PDF" 
          onClick={downloadPDF}
          disabled={loading || !reportData}
        />
      </div>

      {/* Timeframe selector */}
      <div className="agent-reports__filters">
        <div className="timeframe-tabs">
          <button className={timeframe === 7 ? 'active' : ''} onClick={() => setTimeframe(7)}>Last 7 Days</button>
          <button className={timeframe === 30 ? 'active' : ''} onClick={() => setTimeframe(30)}>Last 30 Days</button>
          <button className={timeframe === 90 ? 'active' : ''} onClick={() => setTimeframe(90)}>Last 90 Days</button>
        </div>
      </div>

      {loading ? (
        <div className="loading-state">Generating cloud report...</div>
      ) : reportData ? (
        <>
          {/* Top Stats */}
          <div className="stat-grid" style={{ marginBottom: 'var(--space-6)' }}>
            <StatCard 
              label={`Volume (${timeframe}d)`} 
              value={formatCurrencyTZS(reportData.summary.total_volume)} 
              icon={<TrendingUp size={18} />} 
              color="primary" 
            />
            <StatCard 
              label={`Commissions (${timeframe}d)`} 
              value={formatCurrencyTZS(reportData.summary.total_commission)} 
              icon={<Activity size={18} />} 
              color="success" 
            />
            <StatCard 
              label={`Transactions (${timeframe}d)`} 
              value={reportData.summary.total_count} 
              icon={<PieChartIcon size={18} />} 
              color="accent" 
            />
          </div>

          {/* Charts Row */}
          <div className="agent-reports__charts">
            {/* Volume Trend */}
            <Card padding="md" className="chart-card">
              <h2 className="section-title">Throughput Trend</h2>
              <div className="chart-container">
                <ResponsiveContainer width="100%" height={300}>
                  <AreaChart data={chartData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                    <defs>
                      <linearGradient id="colorVolume" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="5%" stopColor="var(--color-primary)" stopOpacity={0.3}/>
                        <stop offset="95%" stopColor="var(--color-primary)" stopOpacity={0}/>
                      </linearGradient>
                    </defs>
                    <XAxis dataKey="dateStr" tick={{ fontSize: 12, fill: 'var(--color-text-muted)' }} axisLine={false} tickLine={false} />
                    <YAxis tickFormatter={formatCurrencyCompact} tick={{ fontSize: 12, fill: 'var(--color-text-muted)' }} axisLine={false} tickLine={false} />
                    <RechartsTooltip 
                      formatter={(v) => [formatCurrencyTZS(v), 'Volume']}
                      contentStyle={{ background: 'var(--color-surface)', border: '1px solid var(--color-border)', borderRadius: 8, color: 'var(--color-text-primary)' }}
                      itemStyle={{ color: 'var(--color-text-primary)' }}
                    />
                    <Area type="monotone" dataKey="volume" stroke="var(--color-primary)" strokeWidth={3} fillOpacity={1} fill="url(#colorVolume)" />
                  </AreaChart>
                </ResponsiveContainer>
              </div>
            </Card>

            {/* Category Pie */}
            <Card padding="md" className="chart-card">
              <h2 className="section-title">Activity Split</h2>
              <div className="chart-container">
                <ResponsiveContainer width="100%" height={300}>
                  <PieChart>
                    <Pie 
                      data={reportData.category_split} 
                      cx="50%" cy="50%" 
                      innerRadius={60} 
                      outerRadius={90} 
                      paddingAngle={5} 
                      dataKey="value"
                    >
                      {reportData.category_split.map((entry, index) => (
                        <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                      ))}
                    </Pie>
                    <RechartsTooltip 
                      formatter={(v) => [formatCurrencyTZS(v)]}
                      contentStyle={{ background: 'var(--color-surface)', border: '1px solid var(--color-border)', borderRadius: 8, color: 'var(--color-text-primary)' }}
                      itemStyle={{ color: 'var(--color-text-primary)' }}
                    />
                    <Legend iconType="circle" iconSize={8} wrapperStyle={{ fontSize: 12, color: 'var(--color-text-primary)' }} />
                  </PieChart>
                </ResponsiveContainer>
              </div>
            </Card>
          </div>
        </>
      ) : (
        <div className="empty-state">No report data available for this period.</div>
      )}
    </div>
  )
}
